filebeat.prospectors:
- type: log
  paths:
    - /dashboard/lograge_development.log
  json.keys_under_root: true
  
filebeat.registry_file: /etc/registry/mark

output.logstash:
  hosts: ["logstash:5000"]

name: nhsoft

logging.files:
  rotateeverybytes: 10485760 # = 10MB
