filebeat.prospectors:
- type: log
  paths:
    - /demo/lograge_staging.log
  json.keys_under_root: true

filebeat.registry_file: /etc/registry/mark

output.logstash:
  hosts: ["logstash:5044"]

name: 101.132.191.3

logging.files:
  rotateeverybytes: 10485760 # = 10MB
